name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU (For Multi-Arch support if needed)
        uses: orgs/actions/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: orgs/actions/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dtctl
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/go-dtctl-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/go-dtctl-app:${{ github.sha }}
